name: Docs and Sync

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # 选择要使用的 node 版本
          node-version: 22
          # 缓存 pnpm 依赖
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build VuePress site
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          # 部署到指定仓库
          repo: ${{ secrets.GH_RRPO }}
          # 部署到 main 分支
          target_branch: main
          # 部署目录为 VuePress 的默认输出目录
          build_dir: src/.vuepress/dist
        env:
          # 使用 GitHub Token 进行认证
          GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

  sync:
    runs-on: ubuntu-latest
    needs: docs  # 依赖 docs 任务完成

    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: github/lss53/shiwange  # 替换为你的 GitHub 仓库路径
          dst: gitee/lss53/shiwange    # 替换为你的 Gitee 仓库路径
          dst_token: ${{ secrets.GITEE_TOKEN }}  # Gitee 的访问令牌
          force_update: true  # 强制更新